Memory Only Storage Option
Countly/countly-sdk-nodejs pull request #102
Opened 2024-09-18 17:52 UTC by AliRKat

2024-09-19 12:15 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[NodeJS] Option to use memory only for storage](https://trello.com/c/3B9JMGQg/1943-nodejs-option-to-use-memory-only-for-storage)

2024-09-25 04:46 UTC, turtledreams requested changes

2024-09-25 04:46 UTC, turtledreams commented on lib/countly-bulk.js
> +    if (!conf.storage_type) {
so 2 lines above is an example of how we want to handle provided config options

2024-09-25 04:46 UTC, turtledreams commented on test/tests_storage.js
> +        recordValuesToStorageAndValidate(null, cc.storageTypeEnums.MEMORY);
we need SDK running with different storage config options. not testing the module internally. so a real usecase, like initial tests above.

2024-10-02 06:59 UTC, turtledreams requested changes
verify that persistent storage folder is empty in memory tests

2024-10-03 05:55 UTC, turtledreams requested changes

2024-10-03 05:55 UTC, turtledreams commented on lib/countly-storage.js
> +            fs.rmSync(filePath, { recursive: true, force: true }, (err) => {
why a jump from unlink to rmSync?

2024-10-03 10:04 UTC, merged