[SDK-574] Logs sorted out
Countly/countly-sdk-nodejs pull request #21
Opened 2021-12-02 19:35 UTC by turtledreams

![SDK-574](https://user-images.githubusercontent.com/62231246/144490465-a0fb42ed-60ce-4670-b41a-f13796e9ba43.png)

Logs have color now
Log level given at the start
Public func logs gives func info too
Public funcs are covered

2021-12-06 14:23 UTC, ArtursKadikis requested changes
Move the log call to a common "countly-common.js" module.

2021-12-06 14:56 UTC, ArtursKadikis commented
this has merge conflicts

2021-12-07 13:20 UTC, turtledreams commented
![image](https://user-images.githubusercontent.com/62231246/145035714-c957bdbb-95fc-497e-bdd6-016340c4edf7.png)

Module has been created and everything works same.

2021-12-08 13:02 UTC, ArtursKadikis requested changes
"countly-common" needs to be reworked to an object. 
The "require" path should be shortened.

Create a callback for "isLoggingEnabled"

2021-12-15 09:31 UTC, ArtursKadikis requested changes

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk-user.js
> +        cc.log(cc.logLevelEnums.WARNING, "device_id is missing");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk-user.js
> +        cc.log(cc.logLevelEnums.WARNING, "server instance is missing");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk-user.js
> +                cc.log(cc.logLevelEnums.WARNING, "report_feedback, Feedback must contain widget_id property");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk-user.js
> +                cc.log(cc.logLevelEnums.WARNING, "report_feedback, Feedback must contain rating property");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk-user.js
> +                    cc.log(cc.logLevelEnums.WARNING, "report_trace, APM trace must have a", props[i]);
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk.js
> +        cc.log(cc.logLevelEnums.WARNING, "app_key is missing");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk.js
> +        cc.log(cc.logLevelEnums.WARNING, "url is missing");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk.js
> +                cc.log(cc.logLevelEnums.WARNING, "add_request, device_id is missing", query);
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk.js
> +                cc.log(cc.logLevelEnums.WARNING, "add_request, incorrect timestamp format", query);
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk.js
> +                    cc.log(cc.logLevelEnums.WARNING, "add_bulk_request, device_id is missing", query);
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk.js
> +                    cc.log(cc.logLevelEnums.WARNING, "add_bulk_request, incorrect timestamp format", query);
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk.js
> +            cc.log(cc.logLevelEnums.WARNING, "add_event, device_id is missing");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-bulk.js
> +            cc.log(cc.logLevelEnums.WARNING, "add_event, Event must have key property");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly-common.js
> +            console.log(color, level + message, Array.prototype.slice.call(args).join("\n"));
depending on the log level, you should use the available "logWarning" and "logError" functions

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly.js
> +                cc.log(cc.logLevelEnums.WARNING, "Please provide server URL");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly.js
> +            cc.log(cc.logLevelEnums.WARNING, "group_features, Incorrect features: " + features);
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly.js
> +            cc.log(cc.logLevelEnums.WARNING, "check_consent, No feature available for " + feature);
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly.js
> +            cc.log(cc.logLevelEnums.WARNING, "Event must have key property");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly.js
> +            cc.log(cc.logLevelEnums.WARNING, "end_event, Event must have key property");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly.js
> +                cc.log(cc.logLevelEnums.WARNING, "report_conversion, No campaign data found");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly.js
> +                cc.log(cc.logLevelEnums.WARNING, "report_feedback, Feedback must contain widget_id property");
should be "error"

2021-12-15 09:31 UTC, ArtursKadikis commented on lib/countly.js
> +                cc.log(cc.logLevelEnums.WARNING, "report_feedback, Feedback must contain rating property");
should be "error"

2022-01-03 13:44 UTC, ArtursKadikis requested changes
Some lines have "trailing spaces" those should be fixed.

2022-01-04 12:46 UTC, ArtursKadikis requested changes

2022-01-04 12:46 UTC, ArtursKadikis commented on lib/countly.js
> +                cc.log("info", "Countly initialized");
the "level" tag is hardcoded and doesn't reference the variable

2022-01-04 12:46 UTC, ArtursKadikis commented on lib/countly-common.js
> +                    //default log level is info
make "debug" the default

2022-01-04 12:46 UTC, ArtursKadikis commented on lib/countly.js
> +                cc.log("info", "begin_session, Session started");
log level is not linking to the enum

2022-01-04 12:46 UTC, ArtursKadikis commented on lib/countly.js
> +        cc.log("info", "add_consent, Adding consent for " + feature);
log level is not linking to the enum

2022-01-04 12:46 UTC, ArtursKadikis commented on lib/countly.js
> +        cc.log("info", "remove_consent, Removing consent for " + feature);
log level is not linking to the enum

2022-01-04 12:46 UTC, ArtursKadikis commented on lib/countly.js
> +                cc.log("info", "session_duration, Session extended", sec);
log level is not linking to the enum

2022-01-04 12:46 UTC, ArtursKadikis commented on lib/countly.js
> +                cc.log("info", "change_id, Changing ID");
log level is not linking to the enum

2022-01-04 12:46 UTC, ArtursKadikis commented on lib/countly.js
> +            cc.log('info', "Sending HTTP request");
log level is not linking to the enum

2022-01-04 12:46 UTC, ArtursKadikis commented on lib/countly.js
> +                cc.log("info", "end_session, Ending session");
log level is not linking to the enum

2022-01-10 08:05 UTC, ArtursKadikis requested changes
Requires a few tweaks to choosing colors

2022-01-11 07:48 UTC, ArtursKadikis approved these changes

2022-01-11 07:48 UTC, merged