[SDK-365] Internal Limits
Countly/countly-sdk-nodejs pull request #22
Opened 2021-12-03 16:33 UTC by turtledreams

![SDK-365](https://user-images.githubusercontent.com/62231246/144638435-fb85f557-d550-4d3d-a8df-f8a80208792f.png)

Internal limits implemented

2021-12-06 14:55 UTC, ArtursKadikis requested changes
Move the truncation functions to the common module

2021-12-06 14:55 UTC, ArtursKadikis commented
+ there is a merge conflict

2021-12-07 15:09 UTC, turtledreams commented
![image](https://user-images.githubusercontent.com/62231246/145046882-2d435237-847f-449d-bee8-0f9ef1737e30.png)

Functions were moved to common module and everything working as original

2021-12-08 13:01 UTC, ArtursKadikis requested changes
"countly-common" needs to be reworked to an object. 
The "require" path should be shortened.

2022-01-03 13:40 UTC, ArtursKadikis requested changes
Add a few tests that would verify this functionality

2022-01-10 07:33 UTC, turtledreams commented
![image](https://user-images.githubusercontent.com/62231246/148731312-dfa9a27d-0e29-46ff-9188-204f454ea1e5.png)

2022-01-10 07:34 UTC, turtledreams commented
![image](https://user-images.githubusercontent.com/62231246/148731427-f74c13d3-9bbe-40d1-97d8-fde81505d776.png)

2022-01-10 19:39 UTC, ArtursKadikis requested changes
your tests currently are missing usecases that validate the result at the request queue of event queue level.

The expected loop was:
1) set limits
2) init SDK
3) use some SDK feature while exceeding limits
4) verify in RQ or EQ that values are truncated

2022-01-10 19:39 UTC, ArtursKadikis commented on test/test-internal-limit.js
> +        assert.equal(newStr.length, 3);
verify the resulting string and not just it's length. Theoretically the length might match but the content might be garbage

2022-01-10 19:39 UTC, ArtursKadikis commented on test/test-internal-limit.js
> +        assert.equal(newStr.length, 3);
verify the resulting content

2022-01-11 07:49 UTC, ArtursKadikis commented
Merge conflicts

2022-01-20 08:09 UTC, turtledreams commented
![image](https://user-images.githubusercontent.com/62231246/150298450-68cf294f-2868-4320-9d36-834aed803962.png)

Do we need changelog/docs entries for halt?

2022-01-20 09:43 UTC, ArtursKadikis requested changes
Move specific functions to the test function.
Update "halt" comment.

2022-01-20 11:04 UTC, ArtursKadikis approved these changes

2022-01-20 11:04 UTC, merged