[SDK-686] idtype and request t
Countly/countly-sdk-nodejs pull request #39
Opened 2022-04-19 09:36 UTC by turtledreams

checking bulk still, tests are working fine

2022-04-19 09:37 UTC, turtledreams commented
Hmm there are some linting issues. Will fix

2022-04-19 13:09 UTC, ArtursKadikis requested changes
Let's add the "second batch" of tests like in Web

2022-04-19 13:09 UTC, ArtursKadikis commented on lib/countly-common.js
> +     *3 - device ID was provided from location.search
should not exist

2022-04-19 13:09 UTC, ArtursKadikis commented on test/tests_device_id_type.js
> +describe("View test", () => {
sloppy

2022-04-19 13:09 UTC, ArtursKadikis commented on test/tests_device_id_type.js
> +        Countly.change_id("changedID");
add type check before here

2022-05-12 08:51 UTC, ArtursKadikis requested changes

2022-05-12 08:51 UTC, ArtursKadikis commented on CHANGELOG.md
> +- Now you can get the device ID type of the user
* "Added call to..."

2022-05-12 08:51 UTC, ArtursKadikis commented on CHANGELOG.md
> +- Now you can get the device ID of the user
* "Added call to..."

2022-05-12 08:51 UTC, ArtursKadikis commented on lib/countly.js
> + * @param {boolean} [conf.erase_stored_id=false] - set it to true if you want to erase the stored device ID
this should be named correctly. "clearStoredDeviceID"

2022-05-12 08:51 UTC, ArtursKadikis commented on lib/countly.js
> +    var deviceIdType = cc.deviceIdTypeEnums.SDK_GENERATED;
there shouldn't be any default type set

2022-05-12 08:51 UTC, ArtursKadikis commented on lib/countly.js
> +        deviceIdType = cc.deviceIdTypeEnums.SDK_GENERATED;
there shouldn't be any default type set

2022-05-12 08:51 UTC, ArtursKadikis commented on lib/countly.js
> +            if (conf.erase_stored_id) {
add a comment

2022-05-12 08:51 UTC, ArtursKadikis commented on lib/countly.js
>                  if (cluster.isMaster) {
add comments of what is happening afterwards

2022-05-12 08:51 UTC, ArtursKadikis commented on CHANGELOG.md
> +## 22.02.0
major breaking change should be mentioned

2022-05-12 08:51 UTC, ArtursKadikis commented on lib/countly.js
> +                    var storedId = storeGet("cly_id", null);
we should be getting the previous type

2022-05-12 08:51 UTC, ArtursKadikis commented on lib/countly.js
> +            deviceIdType = storeGet("cly_id_type", null);
get this out

2022-05-12 08:51 UTC, ArtursKadikis commented on lib/countly.js
> +    function assignId(storedDeviceId) {
eliminate this function

2022-05-12 08:51 UTC, ArtursKadikis commented on lib/countly.js
> +                        Countly.device_id = assignId(storedId);
split this up into explicit calls

2022-05-13 09:52 UTC, ArtursKadikis approved these changes

2022-05-13 09:52 UTC, merged