Added Storage Module
Countly/countly-sdk-nodejs pull request #96
Opened 2024-08-12 15:01 UTC by AliRKat

2024-08-12 15:05 UTC, AliRKat commented
![](https://github.trello.services/images/mini-trello-icon.png) [[NodeJS] Option to use memory only for storage](https://trello.com/c/3B9JMGQg/1943-nodejs-option-to-use-memory-only-for-storage)

2024-08-13 06:26 UTC, arifBurakDemiray commented on lib/countly-storage.js
> +    defaultPath = "../data/"; // Default path
what was the default path before?
was it ../bulk_data/

2024-08-13 06:30 UTC, arifBurakDemiray commented on lib/countly-storage.js
> +    defaultPath = "../data/"; // Default path
well this is ok but countly and bulk-data defaults are different
If it is not a problem then all cool

2024-08-13 06:30 UTC, arifBurakDemiray commented
And all things looks like failed, could you fix those

2024-08-13 11:48 UTC, turtledreams requested changes
Nice initial work
```
    var asyncWriteLock = false;
    var asyncWriteQueue = [];
```
should be resettable too. check Halt method. pls make sure linting is working. check vscode plugins are all fine. make sure tests work after fixing linting issues (use: npm run test , for tests)

2024-08-13 11:48 UTC, turtledreams commented on lib/countly-bulk.js
> +    var mainDir = path.resolve(__dirname, CountlyStorage.getStoragePath());
this and below should be carried over too

2024-08-14 11:38 UTC, arifBurakDemiray approved these changes
adding tests would be great

2024-08-15 04:17 UTC, merged